//Source https://en.wikipedia.org/wiki/Category:Meteorites_by_name
MeteorNames = [
    "Aarhus",
    "Abee",
    "Adelie Land",
    "Adhi Kot",
    "Adzhi-Bogdo",
    "Santa Rosa de Viterbo",
    "Agen",
    "Akbarpur",
    "Albareto",
    "Allan Hills 84001",
    "Allan Hills A81005",
    "Allegan",
    "Allende",
    "Ambapur Nagla",
    "Andura",
    "Angers",
    "Angra dos Reis",
    "Ankober",
    "Anlong",
    "Annaheim",
    "Appley Bridge",
    "Arbol Solo",
    "Archie",
    "Arroyo Aguiar",
    "Assisi",
    "Atoka",
    "Avanhandava",
    "Bacubirito",
    "Baszkówka",
    "Beardsley",
    "Bellsbank",
    "Bench Crater",
    "Benton",
    "Białystok",
    "Blithfield",
    "Block Island",
    "Bovedy",
    "Brachina",
    "Brahin",
    "Brenham",
    "Buzzard Coulee",
    "Campo del Cielo",
    "Canyon Diablo",
    "Cape York",
    "Carancas",
    "Chambord",
    "Chassigny",
    "Chelyabinsk",
    "Chergach",
    "Chinga",
    "Chinguetti",
    "Claxton",
    "Coahuila",
    "Cranbourne",
    "D'Orbigny",
    "Dronino",
    "Eagle Station",
    "Elbogen",
    "Ensisheim",
    "Esquel",
    "Fukang",
    "Gao–Guenie",
    "Gay Gulch",
    "Gebel Kamil",
    "Gibeon",
    "Goose Lake",
    "Grant",
    "Hadley Rille",
    "Heat Shield Rock",
    "Hoba",
    "Homestead",
    "Hraschina",
    "Huckitta",
    "Imilac",
    "Itqiy",
    "Kaidun",
    "Kainsaz",
    "Karoonda",
    "Kesen",
    "Krasnojarsk",
    "L'Aigle",
    "Lac Dodon",
    "Lake Murray",
    "Loreto",
    "Mackinac Island",
    "Mbozi",
    "Middlesbrough",
    "Millbillillie",
    "Mineo",
    "Monte Milone",
    "Moss",
    "Mundrabilla",
    "Muonionalusta",
    "Murchison",
    "Nakhla",
    "Nantan",
    "Neuschwanstein",
    "Northwest Africa 7034",
    "Northwest Africa 7325",
    "Norton County",
    "Novato",
    "Northwest Africa 3009",
    "Oileán Ruaidh (Mars rock)",
    "Old Woman",
    "Oldenburg",
    "Omolon",
    "Orgueil",
    "Ornans",
    "Osseo",
    "Ourique",
    "Pallasovka",
    "Paragould",
    "Park Forest",
    "Pavlovka",
    "Peace River",
    "Peekskill",
    "Penouille",
    "Polonnaruwa",
    "High Possil",
    "Pultusk",
    "Příbram",
    "Qidong",
    "Richardton",
    "Santa Vitoria do Palmar",
    "Sayh al Uhaymir 169",
    "Seymchan",
    "Shelter Island",
    "Shergotty",
    "Sikhote-Alin",
    "Sołtmany",
    "Springwater",
    "St-Robert",
    "Stannern",
    "Sulagiri",
    "Sutter's Mill",
    "Sylacauga",
    "Tagish Lake",
    "Tamdakht",
    "Tenham",
    "Texas fireball",
    "Tissint",
    "Tlacotepec",
    "Toluca",
    "Treysa",
    "Twannberg",
    "Veliky Ustyug",
    "Vermillion",
    "Weston",
    "Willamette",
    "Winona",
    "Wold Cottage",
    "Yamato 000593",
    "Yamato 691",
    "Yamato 791197",
    "Yardymly",
    "Zaisho",
    "Zaklodzie",
    "towicz"
];
