//Source https://en.wikipedia.org/wiki/Category:Meteorites_by_name
MeteorNames = [
    "Aarhus",
    "Abee",
    "Adelie Land meteorite",
    "Adhi Kot",
    "Adzhi-Bogdo",
    "Santa Rosa de Viterbo Meteorite",
    "Agen",
    "Akbarpur",
    "Albareto",
    "Allan Hills 84001",
    "Allan Hills A81005",
    "Allegan",
    "Allende meteorite",
    "Ambapur Nagla",
    "Andura",
    "Angers",
    "Angra dos Reis meteorite",
    "Ankober",
    "Anlong",
    "Annaheim meteorite",
    "Appley Bridge meteorite",
    "Arbol Solo",
    "Archie",
    "Arroyo Aguiar",
    "Assisi",
    "Atoka meteorite",
    "Avanhandava",
    "Bacubirito Meteorite",
    "Baszkówka",
    "Beardsley meteorite",
    "Bellsbank meteorite",
    "Bench Crater meteorite",
    "Benton meteorite",
    "Białystok",
    "Blithfield meteorite",
    "Block Island meteorite",
    "Bovedy",
    "Brachina meteorite",
    "Brahin",
    "Brenham",
    "Buzzard Coulee meteorite",
    "Campo del Cielo",
    "Canyon Diablo",
    "Cape York meteorite",
    "Carancas meteorite",
    "Chambord meteorite",
    "Chassigny",
    "Chelyabinsk meteorite",
    "Chergach",
    "Chinga meteorite",
    "Chinguetti meteorite",
    "Claxton meteorite",
    "Coahuila meteorite",
    "Cranbourne meteorite",
    "D'Orbigny meteorite",
    "Dronino meteorite",
    "Eagle Station meteorite",
    "Elbogen",
    "Ensisheim",
    "Esquel",
    "Fukang",
    "Gao–Guenie meteorite",
    "Gay Gulch meteorite",
    "Gebel Kamil",
    "Gibeon",
    "Goose Lake meteorite",
    "Grant meteorite",
    "Hadley Rille meteorite",
    "Heat Shield Rock",
    "Hoba meteorite",
    "Homestead",
    "Hraschina meteorite",
    "Huckitta",
    "Imilac",
    "Itqiy meteorite",
    "Kaidun meteorite",
    "Kainsaz meteorite",
    "Karoonda meteorite",
    "Kesen meteorite",
    "Krasnojarsk",
    "L'Aigle",
    "Lac Dodon",
    "Lake Murray Meteorite",
    "Loreto",
    "Mackinac Island meteorite",
    "Mbozi meteorite",
    "Middlesbrough meteorite",
    "Millbillillie",
    "Mineo",
    "Monte Milone",
    "Moss meteorite",
    "Mundrabilla",
    "Muonionalusta",
    "Murchison meteorite",
    "Nakhla meteorite",
    "Nantan meteorite",
    "Neuschwanstein",
    "Northwest Africa 7034",
    "Northwest Africa 7325",
    "Norton County",
    "Novato meteorite",
    "Northwest Africa 3009",
    "Oileán Ruaidh (Mars rock)",
    "Old Woman meteorite",
    "Oldenburg meteorite",
    "Omolon",
    "Orgueil",
    "Ornans",
    "Osseo meteorite",
    "Ourique",
    "Pallasovka",
    "Paragould meteorite",
    "Park Forest",
    "Pavlovka",
    "Peace River",
    "Peekskill meteorite",
    "Penouille meteorite",
    "Polonnaruwa",
    "High Possil meteorite",
    "Pultusk",
    "Příbram meteorite",
    "Qidong",
    "Richardton meteorite",
    "Santa Vitoria do Palmar meteorite",
    "Sayh al Uhaymir 169",
    "Seymchan",
    "Shelter Island meteorite",
    "Shergotty meteorite",
    "Sikhote-Alin meteorite",
    "Sołtmany",
    "Springwater meteorite",
    "St-Robert meteorite",
    "Stannern",
    "Sulagiri",
    "Sutter's Mill meteorite",
    "Sylacauga",
    "Tagish Lake",
    "Tamdakht meteorite",
    "Tenham",
    "Texas fireball",
    "Tissint meteorite",
    "Tlacotepec meteorite",
    "Toluca",
    "Treysa",
    "Twannberg meteorite",
    "Veliky Ustyug",
    "Vermillion meteorite",
    "Weston meteorite",
    "Willamette Meteorite",
    "Winona meteorite",
    "Wold Cottage",
    "Yamato 000593",
    "Yamato 691",
    "Yamato 791197",
    "Yardymly",
    "Zaisho",
    "Zaklodzie meteorite",
    "towicz"
];
